services:

  agent:
    build: ./agent
    ports:
      - "8000:8000"
    # Optional: restart policy
    network_mode: "host"
    depends_on:
      - mcp
 
  mcp:
    build: ./mcp
    ports:
      - "7999:7999"
    # Optional: restart policy
    network_mode: "host"
    depends_on:
      - ddbb
   
  ddbb:
    build: ./ddbb/postgresql
    container_name: postgres-container

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: