services:

  # agent:
  #   build: ./agent
  #   ports:
  #     - "8000:8000"
  #   # Optional: restart policy
  #   network_mode: "host"
  #   depends_on:
  #     - mcp
 
  mcp:
    build: ./mcp
    ports:
      - "7999:7999"
    # Optional: restart policy
    network_mode: "host"
    # ---- Wait for ddbb to be healthy ----
    depends_on:
      ddbb:
        condition: service_healthy
    # -------------------------------------

  ddbb:
    build: ./ddbb/postgresql
    container_name: postgres-container

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    # ---- Health‑check to signal readiness ----
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    # -----------------------------------------
